created framework of record linkage pipeline
dsi-clinic/2024-winter-climate-cabinet-campaign-finance-tracker pull request #22
Opened 2024-02-01 02:15 UTC by nrposner

2024-02-09 20:37 UTC, averyschoen requested changes

2024-02-09 20:37 UTC, averyschoen commented on utils/linkage.py
let's push the pipeline to a different file

2024-02-14 02:28 UTC, nrposner commented on utils/linkage.py
Wait, I assumed this meant pushing the output to another file, and adjusted it to do that. Did this actually mean moving the pipeline to another file?

2024-02-14 15:55 UTC, averyschoen commented
closing for now

2024-02-14 15:55 UTC, closed without merging