(not complete) splink
dsi-clinic/2024-winter-climate-cabinet-campaign-finance-tracker pull request #25
Opened 2024-02-14 16:04 UTC by npashilkar

initial code for splink record linkage function for the persons table

2024-02-15 09:47 UTC, npashilkar commented
i moved my splink code from the notebook i was working in to a .py file. however, i was still getting an error in the notebook that said the model wasn't being fully trained because there was not enough data to train all comparisons. it required at minimum hundreds and ideally thousands of rows. i think someone else is also working on a test file for the other deduplication function so maybe i can take a look at that?

2024-02-19 19:58 UTC, trevorspreadbury commented on utils/linkage.py
> +        dataframe with matched ids of matching rows"""
the spacing on this is strange. Should be no blank line after function signature (`def ..... ):`, and there should be a blank line before args

2024-02-19 19:58 UTC, trevorspreadbury commented on utils/linkage.py
> +        df: dataframe with potential duplicates
Does the df have any required columns? Does this work for both individuals and organizations?

2024-02-20 03:39 UTC, averyschoen requested changes
add your tests to the test_linkage.py file

2024-02-20 03:39 UTC, averyschoen commented on utils/linkage.py
> +def splink_dedupe(df, settings, blocking):
let's add type notation to the inputs and expected outputs

2024-02-22 14:53 UTC, averyschoen requested changes

2024-02-22 14:53 UTC, averyschoen commented on utils/linkage.py
> +    """Given the individuals or organizations dataframes, the corresponding
Given a dataframe and config, dedupe with splink

2024-02-22 14:53 UTC, averyschoen commented on utils/linkage.py
> +        df: individuals or organizations table
generalize

2024-02-22 14:53 UTC, averyschoen commented on utils/linkage.py
> +        dataframe with matched ids of matching rows
more detail on the format of this

2024-02-26 15:00 UTC, averyschoen requested changes

2024-02-26 15:00 UTC, averyschoen commented on utils/linkage.py
> +    """Given a dataframes, the corresponding
shorten this line

2024-02-26 15:00 UTC, averyschoen commented on notebooks/splink.ipynb
remove this

2024-02-28 15:54 UTC, averyschoen requested changes
update to call convert_to_dict(), delete write to csv step, return deduplicated csv with the cols in the schema -- i.e. inputted columns should be what the returned columns are

2024-02-29 14:21 UTC, averyschoen approved these changes

2024-02-29 14:35 UTC, merged