Collect data harvard
dsi-clinic/2024-winter-climate-cabinet-campaign-finance-tracker pull request #56
Opened 2024-04-08 21:45 UTC by ygxu01

I will refine the transform file (split the clean function into clean, standardize, and create_table etc.) and create the pipeline next week :)

2024-04-09 14:51 UTC, sarahwalker10 approved these changes
Message to Yangge: Great work this week, Yangge! One thing: can you please upload the Harvard data you used to the Drive, that way we can all access the data? Thank you! 

Review for Trevor: Yangge found an election results dataset and wrote a script to clean and standardize the data. She did a good job creating functions in the HarvardTransformer class (`src/utils/transform/harvard.py`) that have the same name and purpose as the other state transformer class functions; that way, the pipeline can be run on the Harvard dataset the same way as the other state dfs because it will be calling the same functions to clean and transform the data.

2024-04-11 15:39 UTC, trevorspreadbury requested changes
I'm guessing this is 90% there, but I can't merge this in right now because it doesn't meet minimum viable pull request standard. I can't run the notebook because it depends on a 'harvard.csv' file that is not documented. 

Also the harvard data code should not be part of the StateTransformer pipeline. Ping @sarahwalker10 and I when this is done and we'll merge it in!

2024-04-18 14:10 UTC, sarahwalker10 reviewed
Hi Yangge, Great work!! You've clearly put in a lot of effort not only on the StateTransformers, but also on creating a separate pipeline process for the election data. Here are my comments:
1) In the TA session on Friday I'd like to have you share your screen and run the harvard_eda.ipynb notebook + the transform_election_pipeline.py script you wrote. I am getting an error when I try to run these files, but it could be an issue on my end. Either way we can debug as a group! 
2) I can't open the .docx file that you uploaded for the data/codebook dictionary of the Harvard dataset. I recommend removing the codebook word doc file from GitHub and uploading that to the drive as well, alongside the dataset. Furthermore, please rename the files (both the datafile and the codebook file) to be more clear. 

Also, in the utils/transform/harvard.py script, you commented " # Shall I put this function in this file or in transform file?" on line 94 (in regards to the uuid). Looking at the code for the state transformers, it seems that the uuid assignment is handled within the individual state's cleaning script, before the transform file. So to answer your question, I think you have the function in the right place. 

Great work! I know you are continuing to improve this week, so looking forward to seeing these updates at the TA session!
-Sarah

2024-04-23 17:18 UTC, trevorspreadbury requested changes
There is a lot of good stuff in here. The documentation of the new dataset is good and the election pipeline is well thought out and a unique way of doing it. The standardize_individual_names looks like a good addition, and HumanName looks like a good find. 

I'll echo Sarah and say that the election transform pipeline should be in its own directory (package). 

The main problem is that this is not meeting a minimum viable PR right now. The linter is failing and the code runs into multiple errors when I try to run it. I've added comments that highlight these problems. Make sure you fix these for next week to avoid losing points and do reach out if you need help.

2024-04-23 17:18 UTC, trevorspreadbury commented on src/utils/transform/harvard.py
> +        clean_df = clean_df[clean_df["year"] <=2016 & clean_df["year"] >=2014]
& is evaluated before <= so this is equal to `clean_df[clean_df["year"] <=(2016 & clean_df["year"]) >=2014]` which will lead to an error. Did this run for you?

2024-04-23 17:18 UTC, trevorspreadbury commented on src/utils/transform/harvard.py
> +        data["party"] = data["party"].map(party_map)
theres' no column named party -- is this supposed to be partyt?

2024-04-23 17:18 UTC, trevorspreadbury commented on src/utils/transform/harvard.py
> +    # Shall I put this function in this file or in transform file?
this is fine here

2024-04-30 14:35 UTC, sarahwalker10 reviewed
Great work this week, Yangge! And good incorporation of the feedback from last week. Here are my comments this week:
1. Your code is still not passing the pre-commit checks - do you have any questions about how to check for this or how to make the requested changes by the linter? 
2. A small correction needs to be made on line 8 of `utils/election/constants.py`: because you renamed the harvard data file, you'll need to update this for `HV_FILEPATH`. (However, once this adjustment gets made, your code for `scripts/transform_election_pipeline.py` runs successfully)
3. Your new notebook `notebooks/election_dedupe.ipynb` imports a new package called `altair` : I'm not sure where this is being used in your code, but if you do plan to use it moving forward, it will need to be added to the `requirements.txt` file!

Great job exploring with the splink package by the way!

2024-05-02 19:54 UTC, merged