using jaro-winkler, see if it passes pytest
dsi-clinic/2024-winter-climate-cabinet-campaign-finance-tracker pull request #8
Opened 2024-01-17 02:28 UTC by nrposner

2024-01-17 16:13 UTC, averyschoen approved these changes

2024-01-18 14:36 UTC, averyschoen requested changes

2024-01-18 14:36 UTC, averyschoen commented on utils/linkage.py
> +    return float(td.jaro_winkler(string1.lower(), string2.lower()))
push to think about how to best handle semantic similarity in our usage context...

2024-01-24 02:25 UTC, nrposner commented
Two thoughts:
 - in our corpus of names, we should expect non-matches and variants for first names (bob vs robert) more often than for surnames, which tend to be stable for administrative purposes. Jaro-Winkler prioritizes matches in the early characters of two strings. This is not especially useful for us. 
 - we might think of running jar-winkler on substrings, comparing first and last names, for example. However, in cases where the number of substrings don't match up, this is less useful. 
 - We can improve performance easily by reversing the strings: consider that the JW score of 'bob smith' and 'robert smith' is just 0.72, while 'anantarya smith' and 'robert smith' have a score of .69. If we reverse the strings, this goes to .91 vs .69. This also helps us prioritize surnames, which are more stable and often more identifying.
 - another route would be to switch to a substring matching algorithm. These tend to be slower, but this may not be too much of a problem if we plan to run this relatively rarely.

2024-01-24 02:26 UTC, nrposner commented
> Two thoughts:
> 
> * in our corpus of names, we should expect non-matches and variants for first names (bob vs robert) more often than for surnames, which tend to be stable for administrative purposes. Jaro-Winkler prioritizes matches in the early characters of two strings. This is not especially useful for us.
> * we might think of running jar-winkler on substrings, comparing first and last names, for example. However, in cases where the number of substrings don't match up, this is less useful.
> * We can improve performance easily by reversing the strings: consider that the JW score of 'bob smith' and 'robert smith' is just 0.72, while 'anantarya smith' and 'robert smith' have a score of .69. If we reverse the strings, this goes to .91 vs .69. This also helps us prioritize surnames, which are more stable and often more identifying.
> * another route would be to switch to a substring matching algorithm. These tend to be slower, but this may not be too much of a problem if we plan to run this relatively rarely.

This would also help for address names: the cities and street names of addresses are more identifying than street numbers.

2024-01-24 02:35 UTC, nrposner commented
I may also consider making a variant of jaro-winkler: the current prefix limit is 4 characters, while we may benefit from longer matches at the end. An algorithm that weights matches more strongly based on how close they are to the beginning or end could work.

2024-01-24 15:46 UTC, averyschoen approved these changes

2024-01-24 15:57 UTC, merged